# Generated by Django 6.0.6 on 2026-06-23 17:03

import django.db.models.deletion
import integraciones.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0004_pedido_costo_envio_pedido_descuentos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotuladorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='KLYNEA', max_length=80)),
                ('initial', models.CharField(default='K', max_length=2)),
                ('accent', models.CharField(default='#c0532a', max_length=20)),
                ('label_style', models.CharField(default='classic', max_length=20)),
                ('visual', models.JSONField(blank=True, default=dict)),
                ('logos', models.JSONField(blank=True, default=list)),
                ('active_logo', models.BigIntegerField(blank=True, null=True)),
                ('productos', models.JSONField(blank=True, default=list)),
                ('ai_provider', models.CharField(default='anthropic', max_length=30)),
                ('ai_model', models.CharField(default='claude-haiku-4-5-20251001', max_length=80)),
                ('ai_api_key', integraciones.crypto.EncryptedTextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='Extrae los datos de envío del siguiente texto y responde SOLO con un JSON sin texto adicional ni backticks:\n{"nombres":"nombre completo del destinatario","destino":"dirección completa de entrega","agencia":"empresa courier o agencia de envío","celular":"número de celular","dni":"número de DNI o documento","producto":"descripción del producto o pedido"}\nSi un campo no aparece en el texto, usa "" (cadena vacía). No inventes datos.')),
            ],
            options={
                'verbose_name': 'Configuración del rotulador',
                'verbose_name_plural': 'Configuración del rotulador',
            },
        ),
        migrations.CreateModel(
            name='Rotulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=200)),
                ('destino', models.CharField(blank=True, max_length=400)),
                ('agencia', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=40)),
                ('dni', models.CharField(blank=True, max_length=40)),
                ('producto', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('origen', models.CharField(choices=[('shopify', 'Shopify'), ('mensaje', 'Mensaje'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotulos', to='integraciones.pedido')),
            ],
            options={
                'verbose_name': 'Rótulo',
                'verbose_name_plural': 'Rótulos',
                'ordering': ['-creado'],
            },
        ),
    ]
