# Generated by Django 6.0.6 on 2026-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotulador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotuladorconfig',
            name='ai_base_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
