# Generated by Django 6.0.6 on 2026-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotulador', '0002_rotuladorconfig_ai_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotuladorconfig',
            name='brand',
            field=models.CharField(default='Dashboard', max_length=80),
        ),
    ]
