# Generated by Django 6.0.6 on 2026-06-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0017_pedido_ad_id_origen_pedido_utm_campaign_and_more'),
        ('productos', '0003_productoalias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('es_principal', models.BooleanField(default=False, help_text='Almacén por defecto cuando un pedido no mapea a otro.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('integracion', models.ForeignKey(blank=True, help_text='Fuente o logística que sirve este almacén (para el auto-descuento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes', to='integraciones.integracion')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfigReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_entrega', models.PositiveSmallIntegerField(default=30, help_text='Días que demora una importación en llegar (lead time).')),
                ('dias_seguridad', models.PositiveSmallIntegerField(default=7, help_text='Colchón extra antes de quedarte sin stock.')),
                ('dias_cobertura', models.PositiveSmallIntegerField(default=60, help_text='Cuántos días de venta quieres cubrir al comprar (para la cantidad sugerida).')),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reposicion', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Configuración de reposición',
                'verbose_name_plural': 'Configuración de reposición',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positivo suma, negativo resta.')),
                ('motivo', models.CharField(choices=[('ajuste', 'Ajuste manual'), ('venta', 'Venta (pedido entregado)'), ('importacion', 'Importación recibida'), ('devolucion', 'Devolución')], default='ajuste', max_length=15)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.almacen')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='integraciones.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Stock por almacén',
                'verbose_name_plural': 'Stock por almacén',
                'unique_together': {('producto', 'almacen')},
            },
        ),
    ]
