# Generated by Django 6.0.6 on 2026-06-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0004_atributoproducto_valoratributo_varianteproducto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproducto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='productos.varianteproducto'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productos.varianteproducto'),
        ),
        migrations.AlterUniqueTogether(
            name='stockproducto',
            unique_together={('producto', 'variante', 'almacen')},
        ),
    ]
