# Generated by Django 6.0.6 on 2026-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_dedupe_stock'),
        ('productos', '0004_atributoproducto_valoratributo_varianteproducto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockproducto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stockproducto',
            constraint=models.UniqueConstraint(condition=models.Q(('variante__isnull', True)), fields=('producto', 'almacen'), name='uniq_stock_sin_variante'),
        ),
        migrations.AddConstraint(
            model_name='stockproducto',
            constraint=models.UniqueConstraint(condition=models.Q(('variante__isnull', False)), fields=('producto', 'variante', 'almacen'), name='uniq_stock_con_variante'),
        ),
    ]
