# Generated by Django 6.0.6 on 2026-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('icono', models.CharField(blank=True, max_length=10)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Herramienta externa',
                'verbose_name_plural': 'Herramientas externas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
