# Generated by Django 6.0.6 on 2026-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_compartir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_ver_capacitacion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_ver_herramientas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_ver_inicio',
            field=models.BooleanField(default=True),
        ),
    ]
