# Generated by Django 6.0.6 on 2026-06-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionsistema_vendedor_puede_compartir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_editar_pedidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_ver_pedidos',
            field=models.BooleanField(default=False),
        ),
    ]
