# Generated by Django 6.0.6 on 2026-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracionsistema_vendedor_puede_editar_pedidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='analista_puede_editar_seguimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_editar_seguimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_registrar_pedidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_ver_avances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vendedor_puede_ver_seguimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista'), ('vendedor', 'Vendedor')], default='vendedor', max_length=10),
        ),
    ]
