# Generated by Django 6.0.6 on 2026-06-25 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracionsistema_analista_puede_editar_seguimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedidos_dia', models.PositiveSmallIntegerField(default=0)),
                ('monto_dia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de vendedor',
                'verbose_name_plural': 'Metas de vendedores',
            },
        ),
    ]
