# Generated by Django 6.0.6 on 2026-06-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metavendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pedidos_filtro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
