# Generated by Django 6.0.6 on 2026-06-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil_pedidos_filtro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista'), ('marketing', 'Analista de Marketing'), ('vendedor', 'Vendedor')], default='vendedor', max_length=10),
        ),
    ]
