# Generated by Django 6.0.6 on 2026-06-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ads_filtro',
            field=models.TextField(blank=True, default=''),
        ),
    ]
