# Generated by Django 6.0.6 on 2026-06-27 05:27

import integraciones.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfil_ads_filtro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConexionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Etiqueta para identificarla, ej. "Claude principal"', max_length=80)),
                ('proveedor', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter'), ('custom', 'Personalizada (compatible OpenAI)')], default='anthropic', max_length=20)),
                ('modelo', models.CharField(default='claude-haiku-4-5-20251001', max_length=100)),
                ('base_url', models.CharField(blank=True, default='', help_text='Solo para proveedores compatibles con OpenAI o personalizada.', max_length=200)),
                ('api_key', integraciones.crypto.EncryptedTextField(blank=True, default='')),
                ('activa', models.BooleanField(default=True)),
                ('tokens_entrada', models.BigIntegerField(default=0)),
                ('tokens_salida', models.BigIntegerField(default=0)),
                ('llamadas', models.PositiveIntegerField(default=0)),
                ('ultimo_test_ok', models.BooleanField(blank=True, null=True)),
                ('ultimo_test_msg', models.CharField(blank=True, max_length=255)),
                ('ultimo_test_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conexión de IA',
                'verbose_name_plural': 'Conexiones de IA',
                'ordering': ['nombre'],
            },
        ),
    ]
