# Generated by Django 6.0.6 on 2026-06-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_conexionia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('prompt', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('conexion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='core.conexionia')),
            ],
            options={
                'verbose_name': 'Herramienta con IA',
                'verbose_name_plural': 'Herramientas con IA',
                'ordering': ['nombre'],
            },
        ),
    ]
