# Generated by Django 6.0.6 on 2026-07-02 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_herramientaia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('total_items_sin_match', models.PositiveIntegerField(default=0)),
                ('total_monto_afectado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_matching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte de matching',
                'verbose_name_plural': 'Reportes de matching',
                'ordering': ['-creado'],
            },
        ),
    ]
