# Generated by Django 6.0.6 on 2026-06-23 14:47

import integraciones.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Alias, ej. "Tienda principal PE"', max_length=120)),
                ('etiqueta', models.CharField(blank=True, help_text='Clasificación libre', max_length=80)),
                ('categoria', models.CharField(choices=[('fuente_pedidos', 'Fuente de pedidos'), ('logistica', 'Empresa de logística')], default='fuente_pedidos', max_length=20)),
                ('proveedor', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('wordpress', 'WordPress'), ('otro', 'Otro')], default='shopify', max_length=20)),
                ('proposito', models.CharField(choices=[('extraccion', 'Extracción (leer datos)'), ('actuadora', 'Actuadora (crear/modificar)')], default='extraccion', max_length=20)),
                ('tienda_url', models.CharField(blank=True, max_length=255)),
                ('api_version', models.CharField(blank=True, default='2024-10', help_text='Versión de la API (Shopify)', max_length=20)),
                ('token', integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Admin API access token (Shopify)')),
                ('api_key', integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Consumer key (WooCommerce)')),
                ('api_secret', integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Consumer secret (WooCommerce)')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_test_ok', models.BooleanField(blank=True, null=True)),
                ('ultimo_test_msg', models.CharField(blank=True, max_length=255)),
                ('ultimo_test_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integración',
                'verbose_name_plural': 'Integraciones',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
