# Generated by Django 6.0.6 on 2026-06-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracion',
            name='ultimo_sync_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integracion',
            name='ultimo_sync_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='integracion',
            name='ultimo_sync_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64)),
                ('numero', models.CharField(blank=True, max_length=40)),
                ('nombre_cliente', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('estado_pago', models.CharField(blank=True, max_length=40)),
                ('estado_envio', models.CharField(blank=True, max_length=40)),
                ('fecha_pedido', models.DateTimeField(blank=True, null=True)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='integraciones.integracion')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
                'unique_together': {('integracion', 'external_id')},
            },
        ),
    ]
