# Generated by Django 6.0.6 on 2026-06-23 15:58

import integraciones.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_integracion_ultimo_sync_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integracion',
            name='scopes',
            field=models.CharField(blank=True, default='read_orders', max_length=255),
        ),
        migrations.AlterField(
            model_name='integracion',
            name='api_key',
            field=integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Client ID (Shopify OAuth) / Consumer key (WooCommerce)'),
        ),
        migrations.AlterField(
            model_name='integracion',
            name='api_secret',
            field=integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Client Secret (Shopify OAuth) / Consumer secret (WooCommerce)'),
        ),
        migrations.AlterField(
            model_name='integracion',
            name='token',
            field=integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Access token obtenido por OAuth o Custom App (Shopify)'),
        ),
    ]
