# Generated by Django 6.0.6 on 2026-06-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0003_integracion_scopes_alter_integracion_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pedido',
            name='distrito',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='es_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='order_status_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pais',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('variante', models.CharField(blank=True, max_length=120)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('product_id', models.CharField(blank=True, max_length=64)),
                ('variant_id', models.CharField(blank=True, max_length=64)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integraciones.pedido')),
            ],
        ),
    ]
