# Generated by Django 6.0.6 on 2026-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0004_pedido_costo_envio_pedido_descuentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracion',
            name='scopes',
            field=models.CharField(blank=True, default='read_orders,read_all_orders', max_length=255),
        ),
    ]
