# Generated by Django 6.0.6 on 2026-06-24 01:10

import django.db.models.deletion
import integraciones.crypto
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0005_alter_integracion_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='integracion',
            name='proveedor',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('wordpress', 'WordPress'), ('shalom', 'Shalom'), ('otro', 'Otro')], default='shopify', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfigShalom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_horas', models.PositiveSmallIntegerField(default=6)),
                ('horarios', models.JSONField(blank=True, default=list)),
                ('dias_atras', models.PositiveSmallIntegerField(default=30)),
                ('max_paginas', models.PositiveSmallIntegerField(default=20)),
                ('config_scraper', models.JSONField(blank=True, default=dict)),
                ('codigo_listado', integraciones.crypto.EncryptedTextField(blank=True, default='')),
                ('codigo_validacion', integraciones.crypto.EncryptedTextField(blank=True, default='')),
                ('usar_codigo_avanzado', models.BooleanField(default=False)),
                ('corte_orden', models.CharField(blank=True, max_length=40)),
                ('corte_codigo', models.CharField(blank=True, max_length=40)),
                ('corte_fecha', models.DateField(blank=True, null=True)),
                ('corriendo', models.BooleanField(default=False)),
                ('ultima_corrida', models.DateTimeField(blank=True, null=True)),
                ('ultimo_resultado', models.TextField(blank=True)),
                ('integracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shalom', to='integraciones.integracion')),
            ],
            options={
                'verbose_name': 'Configuración Shalom',
                'verbose_name_plural': 'Configuración Shalom',
            },
        ),
        migrations.CreateModel(
            name='CorridaShalom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='manual', max_length=10)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(blank=True, null=True)),
                ('nuevos', models.PositiveIntegerField(default=0)),
                ('validados', models.PositiveIntegerField(default=0)),
                ('entregados', models.PositiveIntegerField(default=0)),
                ('mensaje', models.TextField(blank=True)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='integraciones.integracion')),
                ('por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='EnvioShalom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('estado', models.CharField(blank=True, max_length=120)),
                ('estado_real', models.CharField(blank=True, max_length=120)),
                ('entregado', models.BooleanField(default=False)),
                ('producto', models.CharField(blank=True, max_length=300)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('dni', models.CharField(blank=True, max_length=40)),
                ('monto', models.CharField(blank=True, max_length=40)),
                ('lugar_entrega', models.CharField(blank=True, max_length=200)),
                ('tipo_envio', models.CharField(blank=True, max_length=120)),
                ('fecha_texto', models.CharField(blank=True, max_length=60)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('en_alerta', models.BooleanField(default=False)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_validacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('integracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='integraciones.integracion')),
            ],
            options={
                'verbose_name': 'Envío Shalom',
                'verbose_name_plural': 'Envíos Shalom',
                'ordering': ['-fecha_pedido', '-primera_vez'],
                'unique_together': {('integracion', 'orden', 'codigo')},
            },
        ),
    ]
