# Generated by Django 6.0.6 on 2026-06-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0006_alter_integracion_proveedor_configshalom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshalom',
            name='cancelar',
            field=models.BooleanField(default=False),
        ),
    ]
