# Generated by Django 6.0.6 on 2026-06-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0007_configshalom_cancelar'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshalom',
            name='progreso',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
