# Generated by Django 6.0.6 on 2026-06-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0008_configshalom_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshalom',
            name='latido',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
