# Generated by Django 6.0.6 on 2026-06-25 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_estrategia'),
        ('integraciones', '0010_pedido_adelanto_pedido_editado_en_pedido_editado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fuente_manual',
            field=models.CharField(blank=True, choices=[('organico', 'Orgánico'), ('publicidad', 'Publicidad - Mensajes'), ('otro', 'Otro')], max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fuente_manual_detalle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integracion',
            name='proveedor',
            field=models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('wordpress', 'WordPress'), ('shalom', 'Shalom'), ('manual', 'Registro manual'), ('otro', 'Otro')], default='shopify', max_length=20),
        ),
        migrations.CreateModel(
            name='PedidoEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=60)),
                ('valor_anterior', models.CharField(blank=True, max_length=300)),
                ('valor_nuevo', models.CharField(blank=True, max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='integraciones.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ediciones_pedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cambio de pedido',
                'verbose_name_plural': 'Historial de pedidos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PedidoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llamada_estado', models.CharField(choices=[('no_contactado', 'No contactado'), ('sin_respuesta', 'Llamado - sin respuesta'), ('contactado', 'Llamado - contactado')], default='no_contactado', max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('recurrente', 'Recurrente'), ('vip', 'VIP'), ('recuperado', 'Recuperado')], max_length=20)),
                ('etapa_embudo', models.CharField(choices=[('creado', 'Pedido creado'), ('contactado', 'Contactado'), ('confirmado', 'Confirmado'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('perdido', 'Perdido/Caído'), ('recuperado', 'Recuperado')], default='creado', max_length=20)),
                ('actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('estrategia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='capacitacion.estrategia')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='integraciones.pedido')),
            ],
            options={
                'verbose_name': 'Seguimiento de pedido',
                'verbose_name_plural': 'Seguimientos de pedidos',
            },
        ),
    ]
