# Generated by Django 6.0.6 on 2026-06-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0011_pedido_fuente_manual_pedido_fuente_manual_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoseguimiento',
            name='llamadas_intentadas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('creado', 'Pedido creado'), ('confirmado', 'Pedido confirmado'), ('despachado', 'Despachado / En camino'), ('entregado', 'Entregado'), ('sin_respuesta', 'Sin respuesta'), ('sin_confirmar', 'No concretó'), ('cancelado', 'Cancelado')], default='creado', max_length=20),
        ),
    ]
