# Generated by Django 6.0.6 on 2026-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0012_pedidoseguimiento_llamadas_intentadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoseguimiento',
            name='llamada_estado',
            field=models.CharField(choices=[('no_contactado', 'No contactado'), ('sin_respuesta', 'Llamado - sin respuesta'), ('contactado', 'Llamado - contactado'), ('contactado_sin_llamada', 'Contactado sin llamada')], default='no_contactado', max_length=30),
        ),
    ]
