# Generated by Django 6.0.6 on 2026-06-25 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0013_alter_pedidoseguimiento_llamada_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoseguimiento',
            name='etapa_embudo',
            field=models.CharField(choices=[('creado', 'Pedido creado'), ('confirmado', 'Pedido confirmado'), ('despachado', 'Despachado / En camino'), ('entregado', 'Entregado'), ('sin_respuesta', 'Sin respuesta'), ('sin_confirmar', 'No concretó'), ('cancelado', 'Cancelado')], default='creado', max_length=20),
        ),
    ]
