# Generated by Django 6.0.6 on 2026-06-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0014_pedido_vendedor_alter_pedidoseguimiento_etapa_embudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='clave',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
