# Generated by Django 6.0.6 on 2026-06-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0015_pedido_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoseguimiento',
            name='etapa_embudo',
        ),
    ]
