# Generated by Django 6.0.6 on 2026-06-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0016_remove_pedidoseguimiento_etapa_embudo'),
        ('productos', '0002_remove_producto_link_web_linkproducto_mediaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ad_id_origen',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utm_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_pedido', to='productos.producto'),
        ),
    ]
