# Generated by Django 6.0.6 on 2026-06-27 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0017_pedido_ad_id_origen_pedido_utm_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_fulfillment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='FilaPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=60)),
                ('producto', models.CharField(blank=True, max_length=300)),
                ('precio', models.CharField(blank=True, max_length=40)),
                ('costo_delivery', models.CharField(blank=True, max_length=40)),
                ('estado_texto', models.CharField(blank=True, max_length=80)),
                ('motivo', models.CharField(choices=[('sin_cruce', 'Sin cruce'), ('dudoso', 'Dudoso')], default='sin_cruce', max_length=12)),
                ('origen', models.CharField(blank=True, max_length=120)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fila pendiente de cruce',
                'verbose_name_plural': 'Filas pendientes de cruce',
                'ordering': ['-creado'],
            },
        ),
    ]
