# Generated by Django 6.0.6 on 2026-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0018_pedido_costo_delivery_pedido_costo_fulfillment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filapendiente',
            name='destino',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
