# Generated by Django 6.0.6 on 2026-06-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0019_filapendiente_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshalom',
            name='log_lineas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
