# Generated by Django 6.0.6 on 2026-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0020_configshalom_log_lineas'),
    ]

    operations = [
        migrations.AddField(
            model_name='configshalom',
            name='capturas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
