# Generated by Django 6.0.6 on 2026-06-13 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('hora', models.CharField(max_length=5)),
                ('mins', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('PEDIDO', 'Pedido'), ('SEGUIM', 'Seguimiento'), ('REPORTE', 'Reporte'), ('TURNO', 'Turno')], max_length=10)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=5)),
                ('flexible', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=200)),
                ('habilidades', models.JSONField(blank=True, default=list)),
                ('descripcion', models.TextField()),
                ('pasos', models.JSONField(default=list)),
                ('tips', models.JSONField(blank=True, default=list)),
                ('titulo_video', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['orden', 'mins'],
            },
        ),
        migrations.CreateModel(
            name='BloqueTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.bloque')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.tarea')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='bloque',
            name='tareas',
            field=models.ManyToManyField(through='capacitacion.BloqueTarea', to='capacitacion.tarea'),
        ),
        migrations.CreateModel(
            name='ProgresoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.tarea')),
            ],
            options={
                'verbose_name': 'Progreso',
                'unique_together': {('usuario', 'tarea', 'fecha')},
            },
        ),
    ]
