# Generated by Django 6.0.6 on 2026-06-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloquetarea',
            name='bloque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloquearea_set', to='capacitacion.bloque'),
        ),
        migrations.AlterField(
            model_name='progresotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_set', to='capacitacion.tarea'),
        ),
    ]
