# Generated by Django 6.0.6 on 2026-06-13 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_alter_bloquetarea_bloque_alter_progresotarea_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitacion.tarea'),
        ),
        migrations.AlterField(
            model_name='progresotarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
