# Generated by Django 6.0.6 on 2026-06-27 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_estrategia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('audiencia', models.CharField(choices=[('general', 'General (todos)'), ('vendedor', 'Vendedor'), ('analista', 'Analista'), ('marketing', 'Marketing')], default='general', max_length=12)),
                ('objetivos', models.TextField(blank=True, help_text='Uno por línea.')),
                ('descripcion', models.TextField(blank=True)),
                ('video_url', models.CharField(blank=True, help_text='Link de YouTube o Vimeo.', max_length=500)),
                ('resumen', models.TextField(blank=True, help_text='Resumen ocultable de la clase.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='AccesoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso_en', models.DateTimeField(auto_now_add=True)),
                ('ultima_en', models.DateTimeField(auto_now=True)),
                ('completado', models.BooleanField(default=False)),
                ('completado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_leccion', to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='capacitacion.leccion')),
            ],
            options={
                'verbose_name': 'Acceso a lección',
                'verbose_name_plural': 'Accesos a lecciones',
                'ordering': ['-ultima_en'],
                'unique_together': {('usuario', 'leccion')},
            },
        ),
    ]
