from django.core.management.base import BaseCommand
from capacitacion.models import Tarea, Bloque, BloqueTarea

TAREAS = [
    {"orden":1,"hora":"08:00","mins":480,"tipo":"TURNO","prioridad":"baja","flexible":False,"nombre":"Arranque del día — revisión general","habilidades":["Organización","Plataforma ecommerce"],"descripcion":"Revisión completa de bandeja de entrada: emails, WhatsApp, plataforma ecommerce y pendientes del día anterior.","pasos":["Abre tu correo y revisa mensajes desde el cierre de ayer","Revisa WhatsApp Business — responde los urgentes de inmediato","Entra a la plataforma y abre el dashboard de pedidos","Anota en tu bitácora los pedidos problemáticos del día","Revisa tu agenda: llamadas programadas y tareas del día"],"tips":[{"k":"info","t":"Los primeros 15 minutos definen el ritmo del día."}],"titulo_video":"Cómo organizar tu arranque del día"},
    {"orden":2,"hora":"08:20","mins":500,"tipo":"PEDIDO","prioridad":"alta","flexible":False,"nombre":"Gestionar pedidos nocturnos pendientes","habilidades":["Gestión de pedidos","Atención al cliente"],"descripcion":"Revisar y procesar todos los pedidos que ingresaron durante la noche o fuera del horario.","pasos":["Filtra pedidos en estado «Nuevo» o «Pendiente de confirmar»","Verifica disponibilidad de stock — si hay quiebre, actúa YA","Confirma los pedidos OK","Para pedidos con problemas: llama al cliente antes de las 09:00","Registra todos los pedidos procesados en tu bitácora"],"tips":[{"k":"warn","t":"Los clientes que compraron de noche esperan confirmación temprano."},{"k":"warn","t":"Quiebre de stock = notifica al cliente en menos de 2 horas."}],"titulo_video":"Cómo procesar pedidos"},
    {"orden":3,"hora":"09:00","mins":540,"tipo":"LLAMADA","prioridad":"alta","flexible":False,"nombre":"Confirmación de pedidos — llamadas salientes","habilidades":["Llamadas salientes","Confirmación de pedidos"],"descripcion":"Bloque de llamadas para confirmar pedidos del día.","pasos":["Genera la lista de pedidos que requieren confirmación verbal","Ordena por prioridad: mayor monto primero","Llama: confirma dirección, horario de entrega y método de pago","Si no contesta: mensaje de voz + WhatsApp","Actualiza el estado del pedido en la plataforma","Anota los que no pudiste contactar para reintentar en la tarde"],"tips":[{"k":"tip","t":"Presentación: «Hola, te llamo de [empresa], soy [nombre]»"},{"k":"info","t":"Si no contesta 2 veces, envía WhatsApp y espera antes de cancelar."}],"titulo_video":"Guía de llamadas de confirmación"},
    {"orden":4,"hora":"09:50","mins":590,"tipo":"PEDIDO","prioridad":"alta","flexible":False,"nombre":"Procesamiento de pedidos nuevos","habilidades":["Gestión de pedidos","Coordinación logística"],"descripcion":"Gestionar todos los pedidos nuevos del turno mañana.","pasos":["Revisa pedidos nuevos ingresados desde el arranque","Verifica que el pago esté confirmado","Confirma stock con almacén","Aprueba el pedido y asigna a ruta de despacho","Envía confirmación al cliente con número de seguimiento","Actualiza el CRM con estado del pedido y ETA"],"tips":[{"k":"warn","t":"Pedido aprobado sin stock = devolución. Verifica SIEMPRE."},{"k":"tip","t":"Usa plantillas de WhatsApp para confirmaciones."}],"titulo_video":"Flujo de procesamiento de pedidos"},
    {"orden":5,"hora":"10:45","mins":645,"tipo":"LLAMADA","prioridad":"media","flexible":True,"nombre":"Recuperación: carritos abandonados","habilidades":["Ventas consultivas","Manejo de objeciones"],"descripcion":"Llamadas proactivas a clientes que no completaron su compra.","pasos":["Extrae clientes con carrito abandonado (últimas 48h)","Prioriza: mayor monto, clientes recurrentes","Llama: «Vi que dejaste algo en tu carrito...»","Escucha la razón del abandono","Ofrece solución: descuento, más info o asistencia en el pago","Si convierte: procesa el pedido en línea"],"tips":[{"k":"tip","t":"El mejor momento es dentro de las 2 horas del abandono."},{"k":"info","t":"No presiones: si dice «voy a pensarlo», agenda para mañana."}],"titulo_video":"Técnicas para recuperar carritos"},
    {"orden":6,"hora":"11:30","mins":690,"tipo":"SEGUIM","prioridad":"media","flexible":False,"nombre":"Seguimiento de entregas en curso","habilidades":["Seguimiento logístico","Servicio postventa"],"descripcion":"Revisar estado de pedidos en tránsito y gestionar incidencias.","pasos":["Filtra pedidos en estado «En camino»","Identifica los con entrega programada para hoy","Detecta pedidos con retraso o incidencia","Para pedidos con problema: llama al cliente ANTES de que él te llame","Coordina con logística la reprogramación","Registra cada incidencia en el CRM"],"tips":[{"k":"info","t":"Contactar proactivamente convierte una mala experiencia en positiva."},{"k":"warn","t":"Pedido con más de 2 días de retraso sin comunicación = crítico."}],"titulo_video":"Gestionar incidencias de entrega"},
    {"orden":7,"hora":"12:00","mins":720,"tipo":"REPORTE","prioridad":"media","flexible":True,"nombre":"Reporte de avance matutino","habilidades":["Reporting","Análisis de KPIs"],"descripcion":"Registro del avance de KPIs de la mañana.","pasos":["Abre la plantilla de reporte diario","Ingresa: N° pedidos, N° llamadas, N° conversiones","Anota problemas de la mañana","Calcula tasa de conversión: conversiones / llamadas × 100","Envía el reporte al supervisor"],"tips":[{"k":"tip","t":"Si los números están bajos, ajusta la estrategia para la tarde."},{"k":"info","t":"Sé honesta: los problemas detectados temprano se resuelven mejor."}],"titulo_video":"Cómo completar el reporte"},
    {"orden":8,"hora":"13:30","mins":810,"tipo":"LLAMADA","prioridad":"media","flexible":True,"nombre":"Llamadas a clientes VIP e inactivos","habilidades":["Fidelización","Ventas relacionales"],"descripcion":"Llamadas de alto valor: VIP para fidelizar e inactivos para recuperar.","pasos":["Lista A (VIP): +3 compras o ticket alto","Lista B (Inactivos): sin compra en 30+ días","Apertura VIP: «Quería contarte que tenemos [novedad]»","Apertura inactivo: «¡Hola! Hace tiempo que no sabemos de ti»","Escucha activamente","Ofrece solución relevante y agenda seguimiento"],"tips":[{"k":"tip","t":"Los VIP son 5× más fáciles de convertir."},{"k":"info","t":"Para inactivos: el «¿todo bien?» humaniza la llamada."}],"titulo_video":"Llamadas de fidelización"},
    {"orden":9,"hora":"14:15","mins":855,"tipo":"PEDIDO","prioridad":"alta","flexible":False,"nombre":"Procesamiento de pedidos de la tarde","habilidades":["Gestión de pedidos","Coordinación"],"descripcion":"Segundo pico de pedidos del día — generalmente el más alto.","pasos":["Revisa todos los pedidos ingresados desde el mediodía","Prioriza por fecha de entrega, método de pago y valor","Verifica stock y aprueba los pedidos OK","Coordina con almacén el despacho urgente","Envía confirmaciones con ETA","Marca los que no se despachan hoy y comunícalo"],"tips":[{"k":"warn","t":"Corte logístico: 16:00. Después, despacho al día siguiente."},{"k":"tip","t":"Con pedidos pendientes a las 15:30, prioriza por fecha prometida."}],"titulo_video":"Pico de pedidos vespertinos"},
    {"orden":10,"hora":"15:00","mins":900,"tipo":"SEGUIM","prioridad":"alta","flexible":False,"nombre":"Devoluciones, cambios y reclamaciones","habilidades":["Manejo de conflictos","Servicio al cliente"],"descripcion":"Gestión de solicitudes de devolución, cambio o reclamación activas.","pasos":["Revisa la bandeja de reclamaciones activas","Entiende el problema ANTES de ofrecer solución","Valida si aplica según política de devoluciones","Si aplica: inicia el proceso y comunica el timeline","Si no aplica: explica con empatía y ofrece alternativa","Cierra cada caso en el CRM"],"tips":[{"k":"warn","t":"Nunca discutas con un cliente enojado. Escucha, valida, soluciona."},{"k":"tip","t":"Frase clave: «Entiendo tu frustración, vamos a resolverlo»."},{"k":"info","t":"Si el caso escala, transfiere al supervisor de inmediato."}],"titulo_video":"Manejar devoluciones"},
    {"orden":11,"hora":"16:00","mins":960,"tipo":"LLAMADA","prioridad":"media","flexible":True,"nombre":"Postventa y encuesta de satisfacción","habilidades":["Postventa","Fidelización"],"descripcion":"Llamadas a clientes que recibieron pedido en los últimos 2 días.","pasos":["Lista de clientes con entrega confirmada en 48h","Llama: «Quería confirmar que recibiste todo bien»","Si hay problema: regístralo como reclamación","Si está satisfecho: pregunta si tiene nueva necesidad","Invita a dejar reseña","Registra en CRM y agenda recompra si mostró interés"],"tips":[{"k":"tip","t":"Las llamadas de postventa generan el doble de fidelidad."},{"k":"info","t":"Máx. 3 min — el cliente lo valora más si no le quita tiempo."}],"titulo_video":"Llamada de postventa efectiva"},
    {"orden":12,"hora":"17:00","mins":1020,"tipo":"REPORTE","prioridad":"media","flexible":True,"nombre":"Cierre de KPIs y reporte final","habilidades":["Reporting","Análisis"],"descripcion":"Registro final de KPIs del día y elaboración del reporte de cierre.","pasos":["Consolida: pedidos, llamadas, conversiones, devoluciones","Calcula KPIs: tasa de conversión, ticket promedio","Anota 3 logros del día y 2 puntos a mejorar","Registra pedidos pendientes para mañana","Envía el reporte al supervisor antes de las 17:30"],"tips":[{"k":"tip","t":"Un buen reporte de cierre tarda 10 min."},{"k":"info","t":"Sé específica: «Hice 18 llamadas, 6 convirtieron (33%)»."}],"titulo_video":"Reporte de cierre"},
    {"orden":13,"hora":"17:30","mins":1050,"tipo":"TURNO","prioridad":"baja","flexible":False,"nombre":"Cierre de jornada y preparación del día siguiente","habilidades":["Organización","Planificación"],"descripcion":"Cierre ordenado: actualizar pendientes y preparar agenda.","pasos":["Verifica que todos los pedidos estén en estado correcto","Anota los pendientes con su prioridad para mañana","Prepara lista de llamadas del día siguiente","Deja el CRM actualizado","Si hay traspaso: comunica los casos urgentes","Cierra sesión en todas las plataformas"],"tips":[{"k":"tip","t":"10 min de planificación al cierre ahorran 30 min de caos mañana."},{"k":"info","t":"El traspaso claro es señal de trabajo en equipo."}],"titulo_video":"Cierre del turno"},
]

BLOQUES = [
    {"label": "Apertura · 08:00–09:00", "orden": 0, "tareas": [1, 2]},
    {"label": "Mañana · 09:00–12:00",   "orden": 1, "tareas": [3, 4, 5, 6]},
    {"label": "Mediodía · 12:00–14:00", "orden": 2, "tareas": [7, 8]},
    {"label": "Tarde · 14:00–18:00",    "orden": 3, "tareas": [9, 10, 11, 12, 13]},
]


class Command(BaseCommand):
    help = 'Carga los datos iniciales de capacitación'

    def handle(self, *args, **options):
        Tarea.objects.all().delete()
        Bloque.objects.all().delete()

        tareas_creadas = {}
        for t in TAREAS:
            tarea = Tarea.objects.create(**t)
            tareas_creadas[t['orden']] = tarea
            self.stdout.write(f'✔ Tarea: {tarea.nombre}')

        for b in BLOQUES:
            bloque = Bloque.objects.create(label=b['label'], orden=b['orden'])
            for i, orden_tarea in enumerate(b['tareas']):
                BloqueTarea.objects.create(
                    bloque=bloque,
                    tarea=tareas_creadas[orden_tarea],
                    orden=i
                )
            self.stdout.write(f'✔ Bloque: {bloque.label}')

        self.stdout.write(self.style.SUCCESS('\n🚀 Datos de capacitación cargados.'))