# Generated by Django 6.0.6 on 2026-06-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0017_pedido_ad_id_origen_pedido_utm_campaign_and_more'),
        ('productos', '0002_remove_producto_link_web_linkproducto_mediaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_externo', models.CharField(max_length=255)),
                ('sku_externo', models.CharField(blank=True, max_length=120)),
                ('external_product_id', models.CharField(blank=True, max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('integracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_productos', to='integraciones.integracion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Alias de producto',
                'verbose_name_plural': 'Alias de productos',
                'ordering': ['nombre_externo'],
                'unique_together': {('integracion', 'nombre_externo')},
            },
        ),
    ]
