# Generated by Django 6.0.6 on 2026-06-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productoalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='productos.producto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=60)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='productos.atributoproducto')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Variante de producto',
                'verbose_name_plural': 'Variantes de producto',
                'ordering': ['orden', 'id'],
                'unique_together': {('producto', 'clave')},
            },
        ),
    ]
