# Generated by Django 6.0.6 on 2026-07-02 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_atributoproducto_valoratributo_varianteproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoalias',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Multiplica la cantidad del alias para expresarla en la unidad canónica del producto. 1 = misma unidad; 2 = cada unidad externa equivale a 2.', max_digits=6),
        ),
        migrations.AddField(
            model_name='productoalias',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias', to='productos.varianteproducto'),
        ),
    ]
