# Generated by Django 6.0.6 on 2026-07-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alias_factor_conversion_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='negocio',
            field=models.CharField(choices=[('klynea', 'Klynea'), ('novashop', 'NovaShop')], default='novashop', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_venta_canonica',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('par', 'Par'), ('kit', 'Kit')], default='unidad', max_length=10),
        ),
    ]
