# Generated by Django 6.0.6 on 2026-07-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0021_configshalom_capturas'),
        ('productos', '0006_producto_unidad_negocio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoalias',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productoalias',
            constraint=models.UniqueConstraint(condition=models.Q(('integracion__isnull', False)), fields=('integracion', 'nombre_externo'), name='uniq_alias_integracion_nombre'),
        ),
        migrations.AddConstraint(
            model_name='productoalias',
            constraint=models.UniqueConstraint(condition=models.Q(('integracion__isnull', True)), fields=('nombre_externo',), name='uniq_alias_global_nombre'),
        ),
    ]
