# Generated by Django 6.0.6 on 2026-06-26 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0016_remove_pedidoseguimiento_etapa_embudo'),
        ('productos', '0002_remove_producto_link_web_linkproducto_mediaproducto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmbralAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpa_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_consecutivos', models.PositiveSmallIntegerField(default=3)),
                ('n8n_webhook_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Umbral de alerta',
                'verbose_name_plural': 'Umbrales de alerta',
            },
        ),
        migrations.CreateModel(
            name='CuentaPublicitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)')], default='meta', max_length=20)),
                ('ad_account_id', models.CharField(max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('integracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_publicitarias', to='integraciones.integracion')),
            ],
            options={
                'verbose_name': 'Cuenta publicitaria',
                'verbose_name_plural': 'Cuentas publicitarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CampanaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=64)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('adset_id', models.CharField(blank=True, max_length=64)),
                ('adset_name', models.CharField(blank=True, max_length=255)),
                ('ad_id', models.CharField(max_length=64)),
                ('ad_name', models.CharField(blank=True, max_length=255)),
                ('incluir_en_extraccion', models.BooleanField(default=False)),
                ('primero_visto', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='anuncios.cuentapublicitaria')),
            ],
            options={
                'verbose_name': 'Anuncio de Meta',
                'verbose_name_plural': 'Anuncios de Meta',
                'ordering': ['campaign_name', 'adset_name', 'ad_name'],
                'unique_together': {('cuenta', 'ad_id')},
            },
        ),
        migrations.CreateModel(
            name='MatchProductoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('sugerido', 'Sugerido automático')], default='manual', max_length=10)),
                ('confianza', models.PositiveSmallIntegerField(default=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('campana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='anuncios.campanameta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_anuncio', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_anuncio', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Match producto-anuncio',
                'verbose_name_plural': 'Matches producto-anuncio',
            },
        ),
        migrations.CreateModel(
            name='AlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('enviada_en', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='anuncios.campanameta')),
            ],
            options={
                'verbose_name': 'Alerta enviada',
                'verbose_name_plural': 'Alertas enviadas',
                'ordering': ['-fecha'],
                'unique_together': {('campana', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='InsightDiarioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impresiones', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('resultados', models.PositiveIntegerField(default=0)),
                ('moneda', models.CharField(blank=True, max_length=10)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='anuncios.campanameta')),
            ],
            options={
                'verbose_name': 'Insight diario (Meta)',
                'verbose_name_plural': 'Insights diarios (Meta)',
                'ordering': ['-fecha'],
                'unique_together': {('campana', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='InsightHorarioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.PositiveSmallIntegerField()),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impresiones', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_hora', to='anuncios.campanameta')),
            ],
            options={
                'verbose_name': 'Insight horario (Meta)',
                'verbose_name_plural': 'Insights horarios (Meta)',
                'ordering': ['-fecha', 'hora'],
                'unique_together': {('campana', 'fecha', 'hora')},
            },
        ),
    ]
