# Generated by Django 6.0.6 on 2026-06-26 22:25

import integraciones.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='access_token',
            field=integraciones.crypto.EncryptedTextField(blank=True, default='', help_text='Token de System User con permiso ads_read (cifrado en BD)'),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='api_version',
            field=models.CharField(default='v21.0', max_length=10),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='ultimo_sync_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='ultimo_sync_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='ultimo_sync_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='ultimo_test_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='ultimo_test_msg',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cuentapublicitaria',
            name='ultimo_test_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuentapublicitaria',
            name='ad_account_id',
            field=models.CharField(help_text='Con prefijo act_, ej. act_123456789', max_length=64, unique=True),
        ),
    ]
