# Generated by Django 6.0.6 on 2026-06-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_cuentapublicitaria_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanameta',
            name='incluir_en_extraccion',
            field=models.BooleanField(default=True),
        ),
    ]
