# Generated by Django 6.0.6 on 2026-06-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_alter_campanameta_incluir_en_extraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanameta',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
