# Generated by Django 6.0.6 on 2026-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_campanameta_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanameta',
            name='proyecto',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
