# Generated by Django 6.0.6 on 2026-07-02 12:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_campanameta_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesPublicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio_usd_pen', models.DecimalField(decimal_places=3, default=Decimal('3.75'), help_text='Soles por 1 USD. Convierte el gasto de Meta a soles para el ROAS real.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Ajustes de publicidad',
                'verbose_name_plural': 'Ajustes de publicidad',
            },
        ),
        migrations.AddField(
            model_name='insightdiariometa',
            name='frequency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='insightdiariometa',
            name='reach',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
